-- MySQL Script generated by MySQL Workbench
-- Tue Oct  6 11:37:52 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema esquema_tareas
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `esquema_tareas` DEFAULT CHARACTER SET utf8 ;
USE `esquema_tareas`;
-- -----------------------------------------------------
-- Table `esquema_tareas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_tareas`.`usuarios` (
	`id_user` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(30) NOT NULL,
	`apellido` VARCHAR(50) NOT NULL,
	`email` VARCHAR(150) NOT NULL,
	`password_hash` VARCHAR(255) NOT NULL,
	`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id_user`),
	UNIQUE INDEX `idusuarios_UNIQUE` (`id_user` ASC) VISIBLE,
	UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `esquema_tareas`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_tareas`.`categorias` (
	`id_categoria` INT NOT NULL AUTO_INCREMENT,
	`nombre_categoria` VARCHAR(50) NOT NULL,
	`desc_categoria` VARCHAR(200) NOT NULL,
	`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id_categoria`),
	UNIQUE INDEX `categoriascol_UNIQUE` (`nombre_categoria` ASC) VISIBLE,
	UNIQUE INDEX `desc_categoria_UNIQUE` (`desc_categoria` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `esquema_tareas`.`prioridades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_tareas`.`prioridades` (
	`id_prioridad` INT NOT NULL AUTO_INCREMENT,
	`nombre_prioridad` VARCHAR(6) NOT NULL,
	`desc_prioridad` VARCHAR(200) NOT NULL,
	`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id_prioridad`),
	UNIQUE INDEX `categoriascol_UNIQUE` (`nombre_prioridad` ASC) VISIBLE,
	UNIQUE INDEX `desc_categoria_UNIQUE` (`desc_prioridad` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `esquema_tareas`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_tareas`.`estados` (
	`id_estado` INT NOT NULL AUTO_INCREMENT,
	`nombre_estado` VARCHAR(15) NOT NULL,
	`desc_estado` VARCHAR(200) NOT NULL,
	`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id_estado`),
	UNIQUE INDEX `categoriascol_UNIQUE` (`nombre_estado` ASC) VISIBLE,
	UNIQUE INDEX `desc_categoria_UNIQUE` (`desc_estado` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `esquema_tareas`.`tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_tareas`.`tareas` (
	`id_tarea` INT NOT NULL AUTO_INCREMENT,
	`titulo` VARCHAR(30) NOT NULL,
	`fecha_limite` DATETIME NOT NULL,
	`desc_tarea` VARCHAR(500) NOT NULL,
	`id_categoria` INT NOT NULL,
	`id_prioridad` INT NOT NULL,
	`id_estado` INT NOT NULL,
	`id_user` INT NOT NULL,
	`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id_tarea`),
	INDEX `fk_tareas_categorias_idx` (`id_categoria` ASC) VISIBLE,
	INDEX `fk_tareas_prioridades1_idx` (`id_prioridad` ASC) VISIBLE,
	INDEX `fk_tareas_estados1_idx` (`id_estado` ASC) VISIBLE,
	INDEX `fk_tareas_usuarios1_idx` (`id_user` ASC) VISIBLE,
	CONSTRAINT `fk_tareas_categorias`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `esquema_tareas`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
	CONSTRAINT `fk_tareas_prioridades1`
    FOREIGN KEY (`id_prioridad`)
    REFERENCES `esquema_tareas`.`prioridades` (`id_prioridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
	CONSTRAINT `fk_tareas_estados1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `esquema_tareas`.`estados` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
	CONSTRAINT `fk_tareas_usuarios1`
    FOREIGN KEY (`id_user`)
    REFERENCES `esquema_tareas`.`usuarios` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `esquema_tareas`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_tareas`.`comentarios` (
	`id_comment` INT NOT NULL AUTO_INCREMENT,
	`contenido` TEXT NOT NULL,
	`id_user` INT NOT NULL,
	`id_tarea` INT NOT NULL,
	`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id_comment`),
	INDEX `fk_comentarios_usuarios1_idx` (`id_user` ASC) VISIBLE,
	INDEX `fk_comentarios_tareas1_idx` (`id_tarea` ASC) VISIBLE,
	CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`id_user`)
    REFERENCES `esquema_tareas`.`usuarios` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
	CONSTRAINT `fk_comentarios_tareas1`
    FOREIGN KEY (`id_tarea`)
    REFERENCES `esquema_tareas`.`tareas` (`id_tarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;